from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


def _fmt_dt(dt: Any) -> str:
    if dt is None:
        return "n/a"
    if isinstance(dt, datetime):
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S %Z")
    return str(dt)


def build_report(report: dict) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, height - 20 * mm, "User Report")

    c.setFont("Helvetica", 10)
    c.drawString(
        20 * mm,
        height - 27 * mm,
        f"Generated at: {_fmt_dt(datetime.now(timezone.utc))}",
    )

    y = height - 45 * mm
    line_h = 7 * mm

    def row(label: str, value: str):
        nonlocal y
        c.setFont("Helvetica-Bold", 11)
        c.drawString(20 * mm, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(60 * mm, y, value)
        y -= line_h

    row("Email", str(report["email"]))
    row("Country", str(report["country"]))
    row("Prostheses total", str(int(report["prosthesis_total"])))
    row("Prostheses active", str(int(report["prosthesis_active"])))
    row("Updated at", _fmt_dt(report.get("updated_at")))

    y -= 5 * mm
    c.setFont("Helvetica", 9)
    c.drawString(
        20 * mm,
        y,
        "Source: ClickHouse reports schema. This PDF is generated by the API.",
    )

    c.showPage()
    c.save()
    return buf.getvalue()
